### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by condaatje** [Harvard-ATG/dce_course_info#1]
It would be nice if someone would take a look over this code (specifically at course_info/views.py) and make sure I'm not breaking every convention/standard/design protocol ever. Thanks Harry.

At its core, Views.py handles all the incoming requests and routes relevant data to the correct template.
The templates are course_info/editor.html and course_info/widget.html

**Comment by xueharry** [comment]
Views.py
-I liked the way you wrote the stern helper to avoid repeating yourself. 
-As for a possible alternative to a [13:] slice for modifying a string, you might want to take a look at using the regular expression library. Specifically, you could use re.sub to substitute "" for "Content-Type: ". 
-Overall, the code is very readable and straightforward. 

I don't really see any issues with either of your templates.

**Comment by condaatje** [comment]
^The re.sub thing worked. Nice.
